name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: shafqat56
          outputs: dist/snake.svg

      - name: Upload Snake.svg
        uses: actions/upload-artifact@v2
        with:
          name: snake-svg
          path: dist/snake.svg

      - name: Commit and Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Updated snake game"
          git push
